### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-AntonellaM#1]
Super @AntonellaM  !!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] We need an h1 tag
- [x] Move the font CSS before your main CSS
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Remove unnecessary vertical scroll.
- [x] Remove right margin of the header that is breaking the horizontal center.
- [x] Finish the header styles for the tablet.
- [x] Finish the main title styles: the typography should be bolder
- [x] Remove unused selectors
- [x] Do not use flex properties on selectors that are not flex parents or flex children.
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

Let me know if you have any doubts ;)

Go for it!!

**Comment by AntonellaM** [comment]
@nasivuela I think I fix everything! Although I have a couple of doubts about scrolling and centering vertically, but I will ask you on Monday! Thanks a lot! :)

**Comment by nasivuela** [comment]
Well done @AntonellaM.

To finish it I will use a class selector instead tag selector for the title. This way if tomorrow you do the contact page and the `h1` has different styles you'll avoid problems.

I trust you will do it, and the work looks really good to me, so I'm closing this ;)

![](https://media.giphy.com/media/8g63zqQ5RPt60/giphy.gif)

**Comment by AntonellaM** [comment]
@nasivuela Thanks for the review!!! I already changed what you suggested.
